### PR TITLE
Add support for ACF WP-CLI

### PR DESCRIPTION
**Pull request by jakub300**

### CODE REVIEW

**Comment by luboskmetko** [comment]
@jakub300 was about to look on this but it's closed now. Isn't it ready yet or something else?

**Comment by jakub300** [comment]
Hey, I implemented export option but when started testing more realistically with x5view I discovered that the workflow will be slightly different then I expected, it will work as follows:
1. Developer creates custom fields locally (they are saved to his database)
2. He exports the to file with cli command
3. x5view or other hosting uses them automatically from file
4. when developer migrates db from hosting to local he loses fields he has in the database, acf starts using fields from files,
5. when developer wants to edit fields he has to import them with command (not implemented) to his database edit, than export to file (via command)

**Comment by jakub300** [comment]
Ok, so I updated things, not yet tested on x5view. Upon further consideration I decided to automatically remove fields from DB after export.

**Comment by jakub300** [comment]
Closing for now, until we add chisel as dependency for projects.

**Pull request closed without merging**
