### PR TITLE
[WIP] Add WordPress Support

### PR DESCRIPTION
**Pull request by jakub300**

### CODE REVIEW

**Comment by luboskmetko** [comment]
@jakub300 great job, looking forward to check how this works. Could you please change the base branch of your PR to the `wp` branch? I would merge it then to test it. Thanks

**Comment by jakub300** [comment]
I updated base but please not merge yet, among other things [it's using my repository](https://github.com/jakub300/generator-chisel/blob/7790cd83016ce3bb7f638194ba4e500c50941cce/generators/wp/templates/composer.json#L8) instead of xfiveco.

**Comment by thymikee** [comment]
@luboskmetko This PR is already done with its requirements. Further improvements to WP workflow should be added as separate PRs from now on.

Please find some time to test it.

Thanks @jakub300 for your awesome work on this, much appreciated!

**Comment by luboskmetko** [comment]
Great, thanks, guys! I'll do.

**Pull request merged**
