### PR TITLE
WP-CLI ❤️

### PR DESCRIPTION
**Pull request by jakub300**
Work in progress implementation of WP-CLI integration.
Currently implemented:
* Offer to drop database if exist
* Create database if doesn't exist
* Install WordPress (downloaded using composer)
* Disable crawling
* Activate Timber
* Activate Theme

TODO:
* [x] Use WP-CLI to download WordPress (is that decided?)
* [x] Fix tests
* [x] Add new tests
* [ ] Remove WP-CLI from repository
* [x] Use WP-CLI to download plugins

We need to decide whether we expect developers to download, install wp-cli manually or we are going to include it in generator or as a dependency some way. At the moment this PR includes WP-CLI so it should work out of box.

### CODE REVIEW

**Comment by luboskmetko** [comment]
Nice, looking forward to test this :) Just one thing - can you create new branches for your PRs directly in the `generator-chisel` repository? In this case I've created such new branch and edited your PR. As we've already discussed I didn't find the way how I could test the PRs from your fork before merging them info master (maybe you have some new suggestion?). While with `generator-chisel` branches it's not a problem.

**Comment by thymikee** [comment]
@luboskmetko you can checkout branches of contributors, here's how you can do it:

screen shot 2016-11-18 at 09 17 19

**Comment by luboskmetko** [comment]
Thanks, Michal!

**Comment by luboskmetko** [comment]
Works really cool. Would it be possible to separate parts of the setup with subtitles somehow like so http://screencast.com/t/SIFRXGgj for better overview of the whole process? Maybe also one above the results line ("Success: Database created." etc)

I like that this works out of box without need to install WP-CLI separately. If there are no issues with it, would be nice to keep it like that.

Regarding installation of WP with WP-CLI vs. Composer, I'm leaning towards getting rid of Composer and installing everything with WP-CLI including plugins. Let's discuss it on Slack and see.

**Comment by luboskmetko** [comment]
@jakub300 cannot you install zips from the premium plugins repo, eg. https://github.com/wp-premium/advanced-custom-fields-pro/archive/master.zip

**Comment by jakub300** [comment]
I suppose I could do that, what about updates?

**Comment by luboskmetko** [comment]
Would it be possible to move `FRONTEND SETUP` title before `Select additional features:` question as those features are related to front-end? If not possible, maybe just change it to `Select additional front-end features:`

Also can success messages be green (eg. `Success: Database created.` and all others)?

**Comment by luboskmetko** [comment]
Developers can do updates from the WP admin as they are used to. Or if necessary we can wrap some WP-CLI functionality to subgenerators but maybe in such case it's easier to use WP-CLI directly but I guess then they would need to install it globally, right?

**Comment by jakub300** [comment]
@luboskmetko @thymikee 
I think everything I was supposed to do here is done. Please test and let me know if you have any problems.
Regarding WP-CLI bundling please think whether you want to put in in the repository or only inside of npm package.
I wasn't sure whether I should activate plugins or only download them, now it's only downloading.

**Comment by thymikee** [comment]
As discussed offline, I think we can go with downloading `wp-cli` into our npm package during `prepublish` hook. 
In the future we can think of refactoring this to work similarly like in `node-sass` or `phantomjs` – downloading while installation.

**Comment by jakub300** [comment]
New subgenerator is here!
With `chisel:wpcli` you can call WP Cli that is inside of Chisel, e.g.. `yo chisel:wpcli plugin list`.

**Comment by luboskmetko** [comment]
@jakub300 cool, I'll test it soon. To your question - you can activate plugins too.

**Comment by luboskmetko** [comment]
Works nice, I just have a few minor comments:

- when user accidentally enters wrong DB user password, the installation ends with DB error after a couple of minutes. Can we test DB credentials right away and allow to fix them before the installation runs?
- I wouldn't output dev-vhost.conf in the console as it shouldn't be a primary way how to setup site locally so it might be confusing. Also it ends a couple of hundreds line up in the command line after installation. 
- can we remove FRONTEND SETUP title, I think at the current position it doesn't make that much sense

**Pull request merged**
