### PR TITLE
Update packages in generated projects

### LINKED ISSUE #353: Update packages version in generated projects

### PR DESCRIPTION
**Pull request by luboskmetko**
Fixes #353

Also added `eslint` and `stylelint` as dependencies. Didn't update Gulp and Webpack to v4 as those produce some errors which require a more detailed look.

### CODE REVIEW

**Comment by jakub300** [comment]
Hey, I looked briefly on packages with breaking updates (based on version numbers) and only thing I wonder is whether olegskl/gulp-stylelint#85 is still an issue?

**Comment by luboskmetko** [comment]
@jakub300 good call. Unfortunately, it's still an issue even in the latest 7.0.0 version, did a few tests with my test case here https://github.com/luboskmetko/test-gulp-stylelint

We could keep 3.9.0 version but that one uses stylelint v7.13.0 and there have been a lot of changes and fixes in stylelint since then (now at v9.1.3). Not sure if that causes any troubles in real projects, but we probably should think how to address this without relying on a fix in `gulp-stylelint`. Should we use some other plugin, eg the webpack one?

cc @arturkot

**Comment by jakub300** [comment]
Could you try to go back to not working version and ignore vendor by passing it to `gulp.src`, something like:
```javascript
gulp.src([path.join(src.base, src.styles), `!${path.join(src.base, 'styles/vendor/**/*')}`])
```
If it works I think it would be enough for us.

**Comment by luboskmetko** [comment]
Actually, it's not only about `vendor` folder, users should be able to easily set specific folders to be ignored, for example whole `src` like described here https://www.getchisel.co/docs/development/code-quality/

**Pull request merged**
