### PR TITLE
Add Disable Emojis Plugin

### LINKED ISSUE #285: Disable WP emojis polyfill
In default WP installation Emojis JS is loaded, we could disable it either by installing https://wordpress.org/plugins/disable-emojis/ plugin or by copying code from it to a new Chisel class. Thoughts?

### PR DESCRIPTION
**Pull request by marcinkrzeminski**
Closes #285 

Disable Emojis plugin is installed and activated with every WordPress project. Tested on my local. 
Please review and test.

### CODE REVIEW

**Comment by jakub300** [comment]
Hey,
* I'm not sure whether we should install it by default or simply offer an option on plugins list? Peronally I'm ok with both.
* If I remember correctly plugin install works with multiple plugins so separated call is not necessary. Please try to add it as next element to the array after timber.
* It looks like you copied test for timber but not updated it with disable-emojis.
* We've fixed the Chisel to link to the readme for specific version so separated PR for readme is not necessary.
* We've recently added contribution guidelines that says `The body of the PR should start with a message that closes the related issues and the actual description in new lines.`

**Comment by marcinkrzeminski** [comment]
Hi,

thanks for the review. It's been fixed. As of the first issue, we agreed that we'll install the plugin by default.

**Comment by jakub300** [comment]
Hey, looks good, one last little thing is indentation in the test.
```
/home/travis/build/xfiveco/generator-chisel/test/wp/wpcli.test.js
  64:5  warning  Expected indentation of 6 spaces but found 4  indent
  65:3  warning  Expected indentation of 4 spaces but found 2  indent
```

**Comment by marcinkrzeminski** [comment]
Fixed

**Pull request merged**
