### PR TITLE
WIP: Pantheon Integration

### PR DESCRIPTION
**Pull request by jakub300**
Should be working, ready for testing.

[Documentation](https://github.com/jakub300/generator-chisel/blob/pantheon/Pantheon.md)

### CODE REVIEW

**Comment by luboskmetko** [comment]
@jakub300 this looks great, but unfortunately I currently don't have time to review this properly with all setup etc. Please proceed without me and maybe ask another WP developer to review it yet (Kuba, Witek?)

**Comment by marcinkrzeminski** [comment]
Do you want to release it in the upcoming release? Unfortunately, I didn't have time so far to test. Should have more time next week to take care of this task.

**Comment by jakub300** [comment]
Considering not much interest not really :)
I would rather focus on JS stuff (webpack, eslint, babel) in the next release.

**Comment by jakub300** [comment]
There is also maintenance aspect (custom pantheon upstream) that needs to be discussed and planned.

**Comment by jakub300** [comment]
Rebased and added few improvements

**Pull request closed without merging**
