### PR TITLE
Add vendor directories, exclude them from linting

### PR DESCRIPTION
**Pull request by arturkot**
Hi everyone,

the purpose of this PR is to provide a way to easily add third party dependencies which, for various reasons, can't be installed from NPM. It usually applies to jQuery plugins or _paid_ scripts which can't be exposed to all users. Same can go for CSS files.

Please let me know your thoughts!

Should (and can) I add any tests for this update? I'd need some directions here. :)

Cheers,

Artur

### CODE REVIEW

**Comment by jakub300** [comment]
How should we use scripts/styles from vendor directories?

**Comment by arturkot** [comment]
@luboskmetko Pushed! It works fine Mac OS. Would be cool to test those ignore files in Windows and Linux as well.

@jakub300 

> How should we use scripts/styles from vendor directories?

By using browserify-shim I think as Browserify is installed by default. Kind of like regular NPM packages. That's the most popular way (and problematic at the same time!) to add scripts judging on the dev help channel. :)

**Comment by luboskmetko** [comment]
hey @arturkot can you please use only `vendor` instead of `src/scripts/vendor` and `src/styles/vendor`? In WP projects there is an option to move the src folder to the theme folder and I don't think the path would work then. Thanks

**Comment by luboskmetko** [comment]
@jakub300 @arturkot I've tested this when `src` moved to a different place, it works when you just use `vendor` folder instead of the whole path.

Agree \rRegarding browserify-shim, but there is already an issue for that here https://github.com/xfiveco/generator-chisel/issues/173

**Comment by arturkot** [comment]
@jakub300 I'll add creating a guide to my to-do list. Thanks for pointing that out!

**Comment by arturkot** [comment]
@luboskmetko Done!

Just need to point out one thing I've noticed. When I choose to move `src` into the theme directory (during yo setup), `gulp build` fails. Seems like the src in theme was incomplete (only some styles were copied). Manually copy-pasting the `src` from root into the theme fixed the issue.

I guess it's resolved in another PR?

Here's my yo config:

```json
{
  "generator-chisel": {
    "config": {
      "name": "Some Random WP project",
      "author": "Artur",
      "projectType": "wp-with-fe",
      "nameSlug": "some-random-wp-project",
      "nameCamel": "Somerandomwpproject",
      "features": {
        "has_jquery": true,
        "has_babel": true
      }
    }
  }
}
```

Screenshot from terminal:

zrzut ekranu 2017-05-11 09 55 37

Theme's src:

zrzut ekranu 2017-05-11 09 57 43

cc @jakub300

**Comment by arturkot** [comment]
@luboskmetko @jakub300 Please disregard the above comment. Sorry! Michal reminded me to rebase the branch which, of course, resolved the problem.

**Pull request merged**
