### PR TITLE
Add \Chisel\Image class with srcset property support.

### PR DESCRIPTION
**Pull request by JakubSzajna**
I've added Image class as an extension to Timber\Image class. Chisel class adds srcset method that returns srcset property for the . This property is generated by WordPress `wp_get_attachment_image_srcset()` function.

### CODE REVIEW

**Comment by luboskmetko** [comment]
@JakubSzajna thanks. I'll try to test this later, just by looking on it, do you think it would make sense to move some image related methods from [Chisel\Media](https://github.com/xfiveco/generator-chisel/blob/master/generators/wp/templates/chisel-starter-theme/Chisel/Media.php) class to this class?

**Comment by JakubSzajna** [comment]
In my opinion, this should work more like a model class for image attachments. This is why I did not move anything from Media to this class as this would require initializing empty image attachment model somewhere in functions.php just to for example define more image sizes. I think Media.php is a more appropriate place for that.

There is also one more thing to check. I'll do that later. I need to check if I can globally replace the \Timber\Image references and force timber to use \Chisel\Image everywhere.

**Comment by luboskmetko** [comment]
Thanks, makes sense.

**Comment by JakubSzajna** [comment]
I've overwritten the Twig Image function to use \Chisel\Image class by default. Unfortunately, there is no way to globally overwrite the Image class used by Timber.

I've also fixed the `get_twig` hook used by Chisel. I've found out that this hook is deprecated. Also using `timber/twig` would not overwrite Twig extensions registered by Timber, so I had to change this hook to `timber/loader/twig` that fires after all extensions are registered by Timber.

This will also allow future users to overwrite functions from Timber. With a previous hook, it was not possible.

**Comment by luboskmetko** [comment]
Fixes #402

**Pull request merged**
