### PR TITLE
Allowing custom proxy URL

### LINKED ISSUE #189: Fix URL for WP setup doesn't work as expected
Steps to reproduce:

1. Run `yo chisel`.
2. Select "WordPress with Front-end".
3. When "Enter URL" shows up, enter a url *different than the default one*.
4. When Yo finishes it's job run `gulp` to fire BrowserSync.
5. It should stuck trying to load `localhost:3000`.

Looks like alternate URL isn't provided for `server.js` scripts which results in an error. Manually adding `"proxyTarget": "[alternate URL]",` inside `.yo-rc` deals with the issue.

### PR DESCRIPTION
**Pull request by luboskmetko**
Tried to fix #189, can you check? Thanks

### CODE REVIEW

**Comment by jakub300** [comment]
Hey Lubos,

Unfortunately it's not that simple, proxy url is specific to the developer (different developers may use different urls) so it must be saved in local file, not normal config. For that I've added support for `.yo-rc-local.json` in b5e3055.

Also, you missed one in [wp-config generator](https://github.com/luboskmetko/generator-chisel/blob/6f96df92ac757fb95b11d2c370ff6af31c166e29/generators/wp-config/index.js#L92) add considering that `proxyTarget` is local and `wp-config` may be run either as part of creation or the part of joining project it adds additional complexity.

**Comment by luboskmetko** [comment]
@jakub300 thanks. What if we disable this prompt for this month's release since it doesn't change anything? I guess there is rarely reason to use different URL than the one generated from the name slug and we should probably spend more time on Docker implementation than this (with Docker it would be obsolete anyway, wouldn't it?)

**Comment by jakub300** [comment]
What do you mean by "disable this prompt"? I would rather keep things as they are right now. We already had situations in when it was necessary in office that's why I added support for `.yo-rc-local.json`, but I think this is enough for now. Regarding docker, yes that will be different and possibly predefined in docker but I think we want to support docker side by side with non-docker flow so I would not call it "obsolete".

**Comment by luboskmetko** [comment]
I meant to hide that prompt for now as it's confusing when it doesn't do what it should. But let's keep it there as a known bug. If you find time you could work on it, as I probably won't find more time for it especially if that's more complex than I thought.

I'm closing this PR.

**Pull request closed without merging**
