### PR TITLE
Wp functions improvements

### PR DESCRIPTION
**Pull request by JakubSzajna**
Please take into account that #185 change in functions.php file would need to be rewritten

### CODE REVIEW

**Comment by jakub300** [comment]
I'm not sure if `to simulate in example ACF values` is ok, `for example` sounds better for me.

**Comment by jakub300** [comment]
@luboskmetko Please review

**Comment by luboskmetko** [comment]
@JakubSzajna @jakub300 nice job just wondering if each class could have a `run` method which would be called from the functions. php? This way we can have self contained classes initialized at one place. Or maybe just use `__construct` method for functionality initialization?

Let me explain on example - let's say I want to add some security settings like `remove_action( 'wp_head', 'wp_generator' );`, I would create a class `Chisel\Security` and if I follow the existing pattern, I would go to `Chisel\Site` and add to `chiselInit` method - `add_action( 'init', array( '\Chisel\Security', 'extend' ) );`

But in fact my Security class has nothing to do with Timber so it shouldn't be initialized from there. Same with `WpExtensions.php`. What you think?

**Comment by luboskmetko** [comment]
A few more notes:

- I would probably use more generic `App` namespace rather than `Chisel`
- maybe `TimberPost` and `TimberSite` instead of just `Post` and `Site`
- move `if ( ! class_exists( 'Timber\\Timber' ) ) {` to TimberSite then
- instead `WpExtensions` we could have two separate classes `RegisterPostTypes` and `RegisterTaxonomies` or a sample class where you could do both but as an example of implementing specific functionality (eg. Team member post type and taxonomy definition)

The goal would be to have everything as loosely coupled as possible where theoretically shouldn't be a problem to remove Timber from the theme and still have a lot of functionality and settings preserved (post types, security, performance settings, etc.)

**Comment by JakubSzajna** [comment]
@luboskmetko thanks for your notes.

First of all, we do not have any elf contained classes here, sothere is nothing to automate instead of \Chisel\Site that is already added to the functions.php. Class constructor is designed for initialization, so I do not think we should invent the wheel again and use other method. If the code gets longer, then it should be splitted into more small methods, but you should still call those methods from the constructor if those should initialize the object.

About your Security class - I was following the timber starter theme code, where registering posts/taxonomies and other actions like this are called from TimberSite class extension:
https://github.com/timber/starter-theme/blob/master/functions.php

About the notes - I was afraid that namespace App could be already used, because as you've said, it is most generic than Chisel ;) This is not a problem until there aren't duplicated names in those other namespaces. That is why I've used Chisel.

> maybe TimberPost and TimberSite instead of just Post and Site

this is the purpose of namespaces there ;)

> move if ( ! class_exists( 'Timber\\Timber' ) ) { to TimberSite then

```
 * Timber Class.
 *
 * Main class called Timber for this plugin.
```
I'd stick with \Timber\Timber class as this is a main plugin class.

About changing WpExtensions - I'd say we should use functionality specific classes if we would want to split  it in parts, because taxonomies and post types are somehow connected, and for me personally it is easier to check taxonomies assigned with my CPT when they are in one file.
The question is, how often you create so much different functionalities in wordpress that you need to split this file into smaller parts?
Is this worth doing that? This could be confusing to some devs. We could of course describe good practices in the README, but I doubt a lot of people reads this section :P

**Comment by luboskmetko** [comment]
thanks @JakubSzajna, I'm pretty ok if we keep certain things like they are eg. Chisel namespace, Post, Site, WpExtensions for CPT and taxonomies, etc.  But still I'd like to propose some code reorganization, please check this https://github.com/luboskmetko/chisel-theme-sample.

What's changed:

- `Helpers` class to help further clean up functions.php
- moving add_theme_support calls to `WpExtensions`. Maybe we could create another class for it, but I think it would be good to keep `Site` and `chiselInit` clean of this and use it only for Timber related stuff, otherwise I can see developers to stuff all filters and actions to this one place
- `Security` is an example of custom class and it's initialized in functions.php, same as WpExtentions
- I've moved the constants to the classes when they are used and change them to properties. Maybe I don't get something but why we use this constants at all? Would it work if developer changes them to something else if they also don't change front-end?

Overall, my goal was that the code itself guides developer to some good practices when writing new functionality. At the same time, I'd like keep them away from the code they don't have to touch unless they know what they are doing like Site class, etc.

Let me know what you think. Thanks

**Comment by JakubSzajna** [comment]
@luboskmetko I generally agree with your points.
Two notes:
* you can use 
```
                return class_exists( 'Timber\\Timber');
```
instead of 
```
		if ( class_exists( 'Timber\\Timber' ) ) {
			return true;
		} else {
			return false;
		}
```
* initially I wanted to place constants in the files where they are used, but I changed my mind and kept them in one place. I'd stick to the "one place idea", but we can create a file or class when all of them would be set to keep them in one place.


```
/**
 * Helpers Security
 * @package Chisel
 */
```
Should be `Class Helpers` :)

**Comment by luboskmetko** [comment]
@JakubSzajna thanks for the fixes, looks good :)

Regarding constants, I'd rather keep them away from the developers sight because changing paths won't work without changing paths in package.json as well. So this is probably not very common task and maybe we could keep them in a separate settings file or class.

Are you ok with updating your PR with some of these changes I've proposed?

**Comment by JakubSzajna** [comment]
@luboskmetko I've added proposed changes. Could you review them to check if you have any more notes? Thanks!

**Comment by luboskmetko** [comment]
@JakubSzajna thanks, looks good to me!

**Pull request merged**
