### PR TITLE
Fix reloading on private template change

### PR DESCRIPTION
**Pull request by danekszy**
Hey guys.

Previous version of private templates exclusion was rather simple and in effect it also excluded those templates from watching and reloading.
Here's my new proposal, which:
- Renames `templates` config field to `templatesBuild`
- Adds `templatesWatch` config field
- Adds a `gulp-filter` dependency
- Excludes private templates from compiling, but doesn't stop the invoked watch task

Let me know what you think...
D.

### CODE REVIEW

**Comment by luboskmetko** [comment]
@danekszy thanks! Wanted to ask what's the difference between templatesBuild and templatesWatch config? I see that in the other there is a JSON file watched, is it preparation for that other PR?

**Comment by danekszy** [comment]
Hey @luboskmetko.
So the one contains globs for what needs to be built (and moved to dist), while the other specifies what needs to be watched in order to initialize the build (and reload).
Regarding JSON... Nice catch! I had this and #57 developed at the same time, but decided to split into 2 PRs, in order to discuss this separately...
Unfortunately #57 is currently depending on this.
Give me a moment and I'll move this change to relevant branch.

**Comment by thymikee** [comment]
Looks good. @danekszy we can merge it before #57

**Comment by jakub300** [comment]
[Here](https://github.com/xfiveco/generator-chisel/blob/52b0fe472b7b3507535448df68acca1f5d0db0dc/generators/app/templates/gulp/tasks/serve.js#L11) is still old variable.

**Comment by danekszy** [comment]
Oh right, I forgot to add this to the PR...
Thanks @jakub300!
I'll let someone else test this and push it through.

**Comment by danekszy** [comment]
@thymikee Can we merge this as well? Merged #57 depends on this...

**Comment by thymikee** [comment]
@danekszy can I ask you to rebase this branch to master?

**Comment by danekszy** [comment]
@thymikee Done. Now the tests are running on CI...

**Pull request merged**
